[package]
name = "bookmark-main"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bookmark-app = { path = "../app" }
iced = { version = "0.7.0", features = ["tokio"] }
