[package]
name = "bookmark-main"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bookmark-app = { path = "../app" }
clap = { version = "4.1.1", features = ["derive"] }
iced = { version = "0.7.0", features = ["tokio"] }
